// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_log_moments
arma::vec cpp_log_moments(const arma::vec& x, int pmax);
RcppExport SEXP _logcumulant_cpp_log_moments(SEXP xSEXP, SEXP pmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type pmax(pmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_log_moments(x, pmax));
    return rcpp_result_gen;
END_RCPP
}
// cpp_log_cumulants
arma::vec cpp_log_cumulants(const arma::vec& m, int pmax);
RcppExport SEXP _logcumulant_cpp_log_cumulants(SEXP mSEXP, SEXP pmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type pmax(pmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_log_cumulants(m, pmax));
    return rcpp_result_gen;
END_RCPP
}
// cpp_M_jacobian
arma::mat cpp_M_jacobian(const arma::vec& m, int pmax);
RcppExport SEXP _logcumulant_cpp_M_jacobian(SEXP mSEXP, SEXP pmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type pmax(pmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_M_jacobian(m, pmax));
    return rcpp_result_gen;
END_RCPP
}
// cpp_V_matrix
arma::mat cpp_V_matrix(const arma::vec& m2p, int pmax);
RcppExport SEXP _logcumulant_cpp_V_matrix(SEXP m2pSEXP, SEXP pmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type m2p(m2pSEXP);
    Rcpp::traits::input_parameter< int >::type pmax(pmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_V_matrix(m2p, pmax));
    return rcpp_result_gen;
END_RCPP
}
// cpp_psd_pinv
Rcpp::List cpp_psd_pinv(const arma::mat& Kd);
RcppExport SEXP _logcumulant_cpp_psd_pinv(SEXP KdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Kd(KdSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_psd_pinv(Kd));
    return rcpp_result_gen;
END_RCPP
}
// cpp_T2_assemble
Rcpp::List cpp_T2_assemble(const arma::vec& d, const arma::mat& Mv, const arma::mat& V, const arma::mat& Jv, const arma::mat& Sigma, int n);
RcppExport SEXP _logcumulant_cpp_T2_assemble(SEXP dSEXP, SEXP MvSEXP, SEXP VSEXP, SEXP JvSEXP, SEXP SigmaSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Mv(MvSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Jv(JvSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_T2_assemble(d, Mv, V, Jv, Sigma, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_logcumulant_cpp_log_moments", (DL_FUNC) &_logcumulant_cpp_log_moments, 2},
    {"_logcumulant_cpp_log_cumulants", (DL_FUNC) &_logcumulant_cpp_log_cumulants, 2},
    {"_logcumulant_cpp_M_jacobian", (DL_FUNC) &_logcumulant_cpp_M_jacobian, 2},
    {"_logcumulant_cpp_V_matrix", (DL_FUNC) &_logcumulant_cpp_V_matrix, 2},
    {"_logcumulant_cpp_psd_pinv", (DL_FUNC) &_logcumulant_cpp_psd_pinv, 1},
    {"_logcumulant_cpp_T2_assemble", (DL_FUNC) &_logcumulant_cpp_T2_assemble, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_logcumulant(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
