# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_log_moments <- function(x, pmax) {
    .Call(`_logcumulant_cpp_log_moments`, x, pmax)
}

cpp_log_cumulants <- function(m, pmax) {
    .Call(`_logcumulant_cpp_log_cumulants`, m, pmax)
}

cpp_M_jacobian <- function(m, pmax) {
    .Call(`_logcumulant_cpp_M_jacobian`, m, pmax)
}

cpp_V_matrix <- function(m2p, pmax) {
    .Call(`_logcumulant_cpp_V_matrix`, m2p, pmax)
}

cpp_psd_pinv <- function(Kd) {
    .Call(`_logcumulant_cpp_psd_pinv`, Kd)
}

cpp_T2_assemble <- function(d, Mv, V, Jv, Sigma, n) {
    .Call(`_logcumulant_cpp_T2_assemble`, d, Mv, V, Jv, Sigma, n)
}

